/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.FinalMediSoft.medicine;

/**
 *
 * @author ankit
 */
import com.FinalMediSoft.admin.AddNewStaff;
import com.FinalMediSoft.main.*;
import com.FinalMediSoft.staff.StaffHome;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class UpdateMedicine extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel tm;

    /**
     * Creates new form AddMedicine
     */
    public UpdateMedicine() {
        initComponents();
        setSize(900,550);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mbatchno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mquantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edate = new com.toedter.calendar.JDateChooser();
        mcompany = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        all = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        meditable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        mprice = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        billing = new javax.swing.JMenu();
        createbill = new javax.swing.JMenuItem();
        viewbills = new javax.swing.JMenuItem();
        stock = new javax.swing.JMenu();
        viewstocks = new javax.swing.JMenuItem();
        medicine = new javax.swing.JMenu();
        addmedicine = new javax.swing.JMenuItem();
        updatemedicine = new javax.swing.JMenuItem();
        deletemedicine = new javax.swing.JMenuItem();
        viewmedicine = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("MediSoft");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(340, 10, 210, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Medicine Batch No* :-");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 20));

        mbatchno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbatchnoActionPerformed(evt);
            }
        });
        jPanel1.add(mbatchno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Medicine Name*:-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 20));

        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Medicine Company*:-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Medicine Quantity*:-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 180, 20));

        mquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mquantityActionPerformed(evt);
            }
        });
        jPanel1.add(mquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Medicine Expiry Date*:-");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 170, 20));
        jPanel1.add(edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 130, -1));

        mcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcompanyActionPerformed(evt);
            }
        });
        jPanel1.add(mcompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, -1));

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 120, -1));

        all.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        all.setText("All");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        jPanel1.add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 120, -1));

        meditable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BATCH_NO", "M_NAME", "M_COMPANY", "QUANTITY", "PRICE", "EXPIRY_DATE"
            }
        ));
        jScrollPane1.setViewportView(meditable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 900, 160));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText(" Medicine Price* :-");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 180, 20));

        mprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpriceActionPerformed(evt);
            }
        });
        jPanel1.add(mprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 530);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 255));

        home.setBackground(new java.awt.Color(51, 51, 255));
        home.setBorder(null);
        home.setText("Home         ");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        billing.setText("    Billing     ");

        createbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createbill.setText("Create Bill");
        billing.add(createbill);

        viewbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewbills.setText("View Bills");
        billing.add(viewbills);

        jMenuBar1.add(billing);

        stock.setText("   Stock  ");

        viewstocks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewstocks.setText("View Stock");
        viewstocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstocksActionPerformed(evt);
            }
        });
        stock.add(viewstocks);

        jMenuBar1.add(stock);

        medicine.setText("   Medicine   ");

        addmedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addmedicine.setText("Add Medicine");
        addmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicineActionPerformed(evt);
            }
        });
        medicine.add(addmedicine);

        updatemedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatemedicine.setText("Update Medicine");
        updatemedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemedicineActionPerformed(evt);
            }
        });
        medicine.add(updatemedicine);

        deletemedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletemedicine.setText("Delete Medicine");
        deletemedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemedicineActionPerformed(evt);
            }
        });
        medicine.add(deletemedicine);

        viewmedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewmedicine.setText("View Medicine");
        viewmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmedicineActionPerformed(evt);
            }
        });
        medicine.add(viewmedicine);

        jMenuBar1.add(medicine);

        jMenu1.setText("                                                                                                                                                                                           ");
        jMenuBar1.add(jMenu1);

        logout.setText(" Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbatchnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbatchnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbatchnoActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void mquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mquantityActionPerformed

    private void mcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcompanyActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
            mname.setText("");
            mcompany.setText("");
            mprice.setText("");
            mquantity.setText("");
            mbatchno.setText("");
            tm.setRowCount(0);
        
        
    }//GEN-LAST:event_clearActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
        String url="jdbc:oracle:thin:@localhost:1521:medisoft";
       try {
           Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection(url,"hr","hrmedi");
       } catch (ClassNotFoundException ex) {
          System.out.println("Driver not loaded");
       } catch (SQLException ex) {
           System.out.println("connection not stablish"+ex);
       }
       
       
        try {
             ps=con.prepareStatement("select * from medicine");
             rs=ps.executeQuery();
            tm=(DefaultTableModel) meditable.getModel();
           tm.setRowCount(0);
           while(rs.next()){
           Object o[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
           tm.addRow(o);
            }
        }catch (SQLException ex) {
            Logger.getLogger(AddNewStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_allActionPerformed

    private void mpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpriceActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String url="jdbc:oracle:thin:@localhost:1521:medisoft";
       try {
           Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection(url,"hr","hrmedi");
       } catch (ClassNotFoundException ex) {
          System.out.println("Driver not loaded");
       } catch (SQLException ex) {
           System.out.println("connection not stablish"+ex);
       }
       
       
        try {
           // int mobile=Integer.parseInt(smobile.getT());
            ps=con.prepareStatement("insert into medicine values(?,?,?,?,?,?)");
            
            ps.setString(1,mbatchno.getText());
            ps.setString(2,mname.getText());
            ps.setString(3,mcompany.getText());
            ps.setString(4,mquantity.getText());
            ps.setString(5,mprice.getText());
            SimpleDateFormat sdf=new SimpleDateFormat("YYYY-MM-DD");
            String date=sdf.format(edate.getDate());
            //ps.setDate(5,sjoindate.getText());
            ps.setString(6,date);
             ps.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(this,"saved successFully");
            mname.setText("");
            mcompany.setText("");
            mprice.setText("");
            mquantity.setText("");
            mbatchno.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddNewStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_updateActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        new StaffHome().setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void viewstocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstocksActionPerformed
        setVisible(false);
        new ViewStock().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewstocksActionPerformed

    private void addmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicineActionPerformed
        setVisible(false);
        new AddMedicine().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_addmedicineActionPerformed

    private void updatemedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemedicineActionPerformed
        setVisible(false);
        new UpdateMedicine().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_updatemedicineActionPerformed

    private void deletemedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemedicineActionPerformed
        setVisible(false);
        new DeleteMedicine().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_deletemedicineActionPerformed

    private void viewmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmedicineActionPerformed
        setVisible(false);
        new ViewMedicine().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_viewmedicineActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Front().setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addmedicine;
    private javax.swing.JButton all;
    private javax.swing.JMenu billing;
    private javax.swing.JButton clear;
    private javax.swing.JMenuItem createbill;
    private javax.swing.JMenuItem deletemedicine;
    private com.toedter.calendar.JDateChooser edate;
    private javax.swing.JMenu home;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu logout;
    private javax.swing.JTextField mbatchno;
    private javax.swing.JTextField mcompany;
    private javax.swing.JMenu medicine;
    private javax.swing.JTable meditable;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mprice;
    private javax.swing.JTextField mquantity;
    private javax.swing.JMenu stock;
    private javax.swing.JButton update;
    private javax.swing.JMenuItem updatemedicine;
    private javax.swing.JMenuItem viewbills;
    private javax.swing.JMenuItem viewmedicine;
    private javax.swing.JMenuItem viewstocks;
    // End of variables declaration//GEN-END:variables
}
