/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.FinalMediSoft.medicine;

import com.FinalMediSoft.admin.AddNewStaff;
import com.FinalMediSoft.main.Front;
import com.FinalMediSoft.staff.StaffHome;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class ViewMedicine extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel tm;

    /**
     * Creates new form ViewMedicine
     */
    public ViewMedicine() {
        initComponents();
        setSize(900,550);
        setResizable(false);
        
        
        String url="jdbc:oracle:thin:@localhost:1521:medisoft";
       try {
           Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection(url,"hr","hrmedi");
       } catch (ClassNotFoundException ex) {
          System.out.println("Driver not loaded");
       } catch (SQLException ex) {
           System.out.println("connection not stablish"+ex);
       }
       
       
        try {
             ps=con.prepareStatement("select * from medicine");
             rs=ps.executeQuery();
            tm=(DefaultTableModel) meditable.getModel();
           tm.setRowCount(0);
           while(rs.next()){
           Object o[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
           tm.addRow(o);
            }
        }catch (SQLException ex) {
            Logger.getLogger(AddNewStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        meditable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        billing = new javax.swing.JMenu();
        createbill = new javax.swing.JMenuItem();
        viewbills = new javax.swing.JMenuItem();
        stock = new javax.swing.JMenu();
        viewstocks = new javax.swing.JMenuItem();
        medicine = new javax.swing.JMenu();
        addmedicine = new javax.swing.JMenuItem();
        updatemedicine = new javax.swing.JMenuItem();
        deletemedicine = new javax.swing.JMenuItem();
        viewmedicine = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ALL MEDICINE DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 360, 50));

        meditable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BATCH_NO", "M_NAME", "M_COMPANY", "QUANTITY", "PRICE", "EXPIRY_DATE"
            }
        ));
        jScrollPane1.setViewportView(meditable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 950, 480));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 255));

        home.setBackground(new java.awt.Color(51, 51, 255));
        home.setBorder(null);
        home.setText("Home         ");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        billing.setText("    Billing     ");

        createbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createbill.setText("Create Bill");
        billing.add(createbill);

        viewbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewbills.setText("View Bills");
        billing.add(viewbills);

        jMenuBar1.add(billing);

        stock.setText("   Stock  ");

        viewstocks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewstocks.setText("View Stock");
        viewstocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstocksActionPerformed(evt);
            }
        });
        stock.add(viewstocks);

        jMenuBar1.add(stock);

        medicine.setText("   Medicine   ");

        addmedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addmedicine.setText("Add Medicine");
        addmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicineActionPerformed(evt);
            }
        });
        medicine.add(addmedicine);

        updatemedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatemedicine.setText("Update Medicine");
        updatemedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemedicineActionPerformed(evt);
            }
        });
        medicine.add(updatemedicine);

        deletemedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletemedicine.setText("Delete Medicine");
        deletemedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemedicineActionPerformed(evt);
            }
        });
        medicine.add(deletemedicine);

        viewmedicine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewmedicine.setText("View Medicine");
        viewmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmedicineActionPerformed(evt);
            }
        });
        medicine.add(viewmedicine);

        jMenuBar1.add(medicine);

        jMenu1.setText("                                                                                                                                                                                           ");
        jMenuBar1.add(jMenu1);

        logout.setText(" Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        new StaffHome().setVisible(true);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void viewstocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstocksActionPerformed
        setVisible(false);
        new ViewStock().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewstocksActionPerformed

    private void addmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicineActionPerformed
        setVisible(false);
        new AddMedicine().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_addmedicineActionPerformed

    private void updatemedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemedicineActionPerformed
        setVisible(false);
        new UpdateMedicine().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_updatemedicineActionPerformed

    private void deletemedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemedicineActionPerformed
        setVisible(false);
        new DeleteMedicine().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_deletemedicineActionPerformed

    private void viewmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmedicineActionPerformed
        setVisible(false);
        new ViewMedicine().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_viewmedicineActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Front().setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addmedicine;
    private javax.swing.JMenu billing;
    private javax.swing.JMenuItem createbill;
    private javax.swing.JMenuItem deletemedicine;
    private javax.swing.JMenu home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu medicine;
    private javax.swing.JTable meditable;
    private javax.swing.JMenu stock;
    private javax.swing.JMenuItem updatemedicine;
    private javax.swing.JMenuItem viewbills;
    private javax.swing.JMenuItem viewmedicine;
    private javax.swing.JMenuItem viewstocks;
    // End of variables declaration//GEN-END:variables
}
